require "cord"

cord.new(function ()
    print()
    print("Resetting log...")
    storm.n.flash_init()
    cord.await(storm.n.flash_write_sp, 768)
    cord.await(storm.os.invokeLater, storm.os.SECOND)
    cord.await(storm.n.flash_write_bp, 768)
    cord.await(storm.os.invokeLater, storm.os.SECOND)
    cord.await(storm.n.flash_write_cp, 768)
    cord.await(storm.os.invokeLater, storm.os.SECOND)
    local new_sp = cord.await(storm.n.flash_read_sp)
    print("New sp = " .. new_sp)
    local new_bp = cord.await(storm.n.flash_read_bp)
    print("New bp = " .. new_bp)
    local new_cp = cord.await(storm.n.flash_read_cp)
    print("New cp = " .. new_cp)
end)

cord.enter_loop()
